export const seedDepartments = [
  "Amaliy informatika",
  "Amaliy kosmetologiya",
  "Aniq fanlar",
  "Arxitektura va shaharsozlik",
  "Axborot texnologiyalari",
  "Bank ishi va buxgalteriya hisobi",
  "Ijtimoiy gumanitar fanlar",
  "Ingliz tili",
  "Yo'l harakati",
  "Klinik fanlar",
  "Koreys tili filologiyasi",
  "Qurilish",
  "Libos dizayni",
  "Maktabgacha va boshlang'ich ta'lim metodikasi",
  "Maxsus pedagogika",
  "Mashinasozlik texnologiyasi",
  "Menejment va marketing",
  "Moliya",
  "Pedagogika va psixologiya",
  "Rus tili",
  "Tarjima nazariyasi va amaliyoti",
  "Tarix",
  "Terapevtik stomatologiya",
  "Tibbiy biologik fanlar",
  "Tibbiy fundamental fanlar",
  "Turizm",
  "Xirurgik fanlar",
  "Xalqaro iqtisodiyot",
  "Kimyo va biologiya",
  "Energetika va amaliy fanlar",
  "Pediatrik fanlar",
  "Rang tasvir",
] as const;

export const seedScientificDirections = [
  "Arxitektura",
  "Iqtisodiyot",
  "Pedagogika",
  "Psixologiya",
  "San'at",
  "Tibbiyot",
  "Muhandislik",
  "Axborot texnologiyalari",
  "Filologiya",
  "Matematika",
  "Biologiya",
  "Kimyo",
  "Turizm",
] as const;

export const seedEmailTemplates = [
  {
    key: "submission_received",
    name: "Ariza qabul qilindi",
    subject: "Arizangiz qabul qilindi",
    body: "Hurmatli muallif, arizangiz tizimga muvaffaqiyatli qabul qilindi va ko'rib chiqish navbatiga qo'shildi.",
  },
  {
    key: "review_assigned",
    name: "Taqriz biriktirildi",
    subject: "Sizga yangi taqriz topshirildi",
    body: "Hurmatli taqrizchi, sizga yangi qo'lyozma ekspertiza uchun biriktirildi.",
  },
  {
    key: "revision_required",
    name: "Tuzatish talab qilindi",
    subject: "Qo'lyozmangiz bo'yicha tuzatish talab qilindi",
    body: "Hurmatli muallif, qo'lyozmangiz bo'yicha tuzatishlar kiritish so'raldi. Iltimos, izohlar bilan tanishing.",
  },
  {
    key: "submission_accepted",
    name: "Ariza qabul qilindi",
    subject: "Qo'lyozmangiz qabul qilindi",
    body: "Tabriklaymiz, qo'lyozmangiz nashrga tavsiya etildi.",
  },
  {
    key: "submission_rejected",
    name: "Ariza rad etildi",
    subject: "Qo'lyozmangiz rad etildi",
    body: "Afsuski, qo'lyozmangiz joriy bosqichda rad etildi. Batafsil izohlar tizimda mavjud.",
  },
  {
    key: "submission_published",
    name: "Ariza nashr qilindi",
    subject: "Qo'lyozmangiz nashr qilindi",
    body: "Tabriklaymiz, qo'lyozmangiz muvaffaqiyatli nashr qilindi.",
  },
] as const;
